on:
  push:
    branch:
      - 'main'

name: Deploy to Nelify

jobs:
  build:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install Lunr extension"
        run: "npm install"
      - name: "Build"
        id: build
        run: bash build.sh
      - name: "Tree"
        run: "tree build"